proto_outdir = "./grpc-deps/target/protobuf_external_src"

[[dependencies]]
target = "github.com/coralogix/rules-api-protobuf/"
revision = "v0.9"

[[dependencies]]
target = "github.com/coralogix/alerts-api-protobuf/"
revision = "v0.4"
