apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  config.path: {{ printf "config/%s" .Values.config.location }}
  operator.conf: |-
    include required(classpath("shared.conf"))

    grpc {
      clients {
        rulegroups {
          name = {{ .Values.config.coralogixApi.host }}
          port = {{ .Values.config.coralogixApi.port }}
          tls = {{ .Values.config.coralogixApi.tls }}
          token = ${RULES_API_TOKEN}
          headers {
            X-Coralogix-API: rules
          }
        }

        alerts {
          name = {{ .Values.config.coralogixApi.host }}
          port = {{ .Values.config.coralogixApi.port }}
          tls = {{ .Values.config.coralogixApi.tls }}
          token = ${RULES_API_TOKEN}
          headers {
            X-Coralogix-API: alerts
          }
        }
    
        tags {
          name = {{ .Values.config.coralogixApi.host }}
          port = {{ .Values.config.coralogixApi.port }}
          tls = {{ .Values.config.coralogixApi.tls }}
          token = ${RULES_API_TOKEN}
          headers {
            X-Coralogix-API: tags
          }
        }
      }
    }

    resources {
      defaultBuffer = {{ .Values.config.resources.defaultBuffer }}
      rulegroups = [
        {{- range .Values.config.resources.rulegroups }}
        {
          namespace = {{ .namespace }}
          {{ if .buffer }}buffer = {{ .buffer }}{{ end }}
        },
        {{- end }}
      ]

      coralogixLoggers = [
        {{- range .Values.config.resources.coralogixLoggers }}
        {
          namespace = {{ .namespace }}
          {{ if .buffer }}buffer = {{ .buffer }}{{ end }}
        },
        {{- end }}
      ]

      alerts = [
        {{- range .Values.config.resources.alerts }}
        {
          namespace = {{ .namespace }}
          {{ if .buffer }}buffer = {{ .buffer }}{{ end }}
        },
        {{- end }}
      ]
    
      tags = [
        {{- range .Values.config.resources.tags }}
        {
          namespace = {{ .namespace }}
          {{ if .buffer }}buffer = {{ .buffer }}{{ end }}
        },
        {{- end }}
      ]
    
    }
    
    alertLabels = [
      {{- range .Values.config.alertLabels }}
        {{ . | quote }},
      {{- end }}  
    ]


