{{- if (.Values.serviceAccount.create) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template ".chart.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-role
  labels:
    app: {{ .Chart.Name }}
rules:
  - apiGroups:
      - coralogix.com
    resources:
      - rulegroupsets
      - rulegroupsets/status
    verbs: ["get", "watch", "update"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["get", "list", "create", "update"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-role-binding
  labels:
    app: {{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template ".chart.serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: {{ .Chart.Name }}-role

{{- end }}
