{{- if (.Values.serviceAccount.create) -}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template ".chart.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-role
  labels:
    app: {{ .Chart.Name }}
rules:
  - apiGroups:
      - coralogix.com
    resources:
      - rulegroupsets
      - rulegroupsets/status
    verbs: ["get", "watch", "update"]
  - apiGroups:
      - loggers.coralogix.com
    resources:
      - coralogixloggers
      - coralogixloggers/status
      - coralogixloggers/finalizers
    verbs: ["get", "watch", "update"]
  - apiGroups:
      - coralogix.com
    resources:
      - alertsets
      - alertsets/status
    verbs: ["get", "watch", "update"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["get", "list", "create", "update"]
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs: [ "get", "list", "create", "update" ]
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs: [ "get", "list", "create", "update" ]
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs: [ "get", "list", "create", "update" ]
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs: [ "get", "list", "create", "update", "delete" ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-role-binding
  labels:
    app: {{ .Chart.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ template ".chart.serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: {{ .Chart.Name }}-role

{{- end }}
