apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: alertsets.coralogix.com
spec:
  group: coralogix.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - alerts
              properties:
                alerts:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - isActive
                      - severity
                    properties:
                      name:
                        type: string
                        x-scala-type: AlertName
                      description:
                        type: string
                      isActive:
                        type: boolean
                      severity:
                        type: string
                        enum:
                          - INFO
                          - WARNING
                          - CRITICAL
                      expiration:
                        type: string
                        format: date
                      condition:
                        type: object
                        required:
                          - type
                        properties:
                          type:
                            type: string
                            enum:
                              - IMMEDIATE
                              - LESS_THAN
                              - MORE_THAN
                              - MORE_THAN_USUAL
                              - NEW_VALUE
                          parameters:
                            description: Condition parameters, required for all types except IMMEDIATE
                            type: object
                            required:
                              - timeframe
                            properties:
                              threshold:
                                type: number
                                format: double
                                minimum: 0
                              timeframe:
                                description: The valid timeframes depend on the condition type. For NEW_VALUE alerts it can be 12H..3M, otherwise 5Min..24H
                                type: string
                                enum: ["5Min", "10Min", "20Min", "30Min", "1H", "2H", "3H", "4H", "6H", "12H", "24H", "48H", "72H", "1W", "1M", "2M", "3M"]
                              groupBy:
                                description: Required for NEW_VALUE conditions
                                type: string
                              notifyOnResolved:
                                descprition: Sends resolve notification when the alert criteria that you defined is no longer met
                                type: boolean
                                default: true
                              metricAlertPromqlParameters:
                                description: Data for defining promql metric
                                type: object
                                properties:
                                  promqlText:
                                    type: string
                                  arithmeticOperatorModifier:
                                    type: integer
                                    format: int32
                                  sampleThresholdPercentage:
                                    type: integer
                                    format: int32
                                  nonNullPercentage:
                                    type: integer
                                    format: int32
                                  swapNullValues:
                                    type: boolean
                      notifications:
                        type: object
                        properties:
                          emails:
                            type: array
                            items:
                              type: string
                              x-scala-type: EmailAddress
                          integrations:
                            type: array
                            items:
                              type: string
                              x-scala-type: IntegrationAlias

                      filters:
                        type: object
                        required:
                          - filterType
                        properties:
                          filterType:
                            type: string
                            enum:
                              - TEXT
                              - TEMPLATE
                              - RATIO
                              - METRIC
                          severities:
                            type: array
                            items:
                              type: string
                              enum:
                                - DEBUG
                                - VERBOSE
                                - INFO
                                - WARNING
                                - ERROR
                                - CRITICAL
                          metadata:
                            type: object
                            properties:
                              categories:
                                type: array
                                items:
                                  type: string
                                  x-scala-type: CategoryName
                              applications:
                                type: array
                                items:
                                  type: string
                                  x-scala-type: ApplicationName
                              subsystems:
                                type: array
                                items:
                                  type: string
                                  x-scala-type: SubsystemName
                              computers:
                                type: array
                                items:
                                  type: string
                                  x-scala-type: ComputerName
                              classes:
                                type: array
                                items:
                                  type: string
                                  x-scala-type: ClassName
                              methods:
                                type: array
                                items:
                                  type: string
                                  x-scala-type: MethodName
                              ipAddresses:
                                type: array
                                items:
                                  type: string
                                  x-scala-type: IPAddress

                          alias:
                            type: string
                            x-scala-type: QueryAlias
                          text:
                            type: string
                            x-scala-type: Query
                          ratioAlerts:
                            type: array
                            items:
                              type: object
                              properties:
                                alias:
                                  type: string
                                  x-scala-type: QueryAlias
                                text:
                                  type: string
                                  x-scala-type: Query
                                severities:
                                  type: array
                                  items:
                                    type: string
                                    enum:
                                      - DEBUG
                                      - VERBOSE
                                      - INFO
                                      - WARNING
                                      - ERROR
                                      - CRITICAL
                                applications:
                                  type: array
                                  items:
                                    type: string
                                    x-scala-type: ApplicationName
                                subsystems:
                                  type: array
                                  items:
                                    type: string
                                    x-scala-type: SubsystemName
                      notifyEvery:
                        description: The suppress time for an alert in seconds
                        type: number
                        format: double
                        x-scala-type: Seconds

                      activeWhen:
                        type: object
                        required:
                          - timeframes
                        properties:
                          timeframes:
                            type: array
                            items:
                              type: object
                              properties:
                                daysOfWeek:
                                  type: array
                                  items:
                                    type: string
                                    enum:
                                      - MONDAY
                                      - TUESDAY
                                      - WEDNESDAY
                                      - THURSDAY
                                      - FRIDAY
                                      - SATURDAY
                                      - SUNDAY
                                range:
                                  type: object
                                  required:
                                    - start
                                    - end
                                  properties:
                                    start:
                                      type: string
                                      x-scala-type: Time
                                    end:
                                      type: string
                                      x-scala-type: Time

                      notificationPayloadFilters:
                        type: array
                        items:
                          type: string
                          x-scala-type: PayloadFilter

            status:
              type: object
              properties:
                # Maps the name of alerts in the spec to coralogix IDs. Alerts without an associated
                # Coralogix alert are omitted
                alert-ids:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - id
                    properties:
                      name:
                        type: string
                        x-scala-type: AlertName
                      id:
                        type: string
                        x-scala-type: AlertId
                last-uploaded-generation:
                  type: integer
                  format: int64
                failures:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - failure
                    properties:
                      name:
                        type: string
                        x-scala-type: AlertName
                      failure:
                        type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: alertsets
    singular: alertset
    kind: AlertSet
