apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: usersettingssets.coralogix.com
spec:
  group: coralogix.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - users
              properties:
                users: # TODO for starters copy the structure from users v2beta1
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - isActive
                      - severity
                    properties:
                      name:
                        type: string
                        x-scala-type: AlertName
                      description:
                        type: string
                      isActive:
                        type: boolean
                      severity:
                        type: string
                        enum:
                          - INFO
                          - WARNING
                          - CRITICAL
# TODO still from alerts
            status:
              type: object
              properties:
                # Maps the name of alerts in the spec to coralogix IDs. Alerts without an associated
                # Coralogix alert are omitted
                alert-ids:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - id
                    properties:
                      name:
                        type: string
                        x-scala-type: AlertName
                      id:
                        type: string
                        x-scala-type: AlertId
                last-uploaded-generation:
                  type: integer
                  format: int64
                failures:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - failure
                    properties:
                      name:
                        type: string
                        x-scala-type: AlertName
                      failure:
                        type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: userssets
    singular: usersset
    kind: UsersSet
