config:
  coralogixApi:
    host: grpc-api.coralogix.com
    port: 443
    tls: true
  location: operator.conf
  resources:
    defaultBuffer: 1024
    rulegroups: []
image:
  pullPolicy: IfNotPresent
  repository: coralogixrepo
  tag: not-set # set by the release process on the fly
replicaCount: 1
resources:
  cpus: 1
  memoryMb: 1024
service:
  port: 9090
serviceAccount:
  create: true
serviceMonitor:
  create: false
  interval: 20s
  namespace: monitoring
  port: 8080
