replicaCount: 1

image:
  repository: coralogixrepo
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true

service:
  port: 9090
serviceMonitor:
  port: 8080

resources:
  memoryMb: 1024
  cpus: 1

config:
  location: operator.conf
  coralogixApi:
    host: grpc-api.coralogix.net
    port: 443
    tls: true
