config:
  coralogixApi:
    host: grpc-api.coralogix.com
    port: 443
    tls: true
  location: operator.conf
  resources:
    defaultBuffer: 1024 # applied to all resources/namespaces;
    rulegroups: []
      # - namespace: default
      #   buffer: 1024
image:
  pullPolicy: IfNotPresent
  repository: coralogixrepo
  tag: 0.1.13
replicaCount: 1
resources:
  cpus: 1
  memoryMb: 1024
service:
  port: 9090
serviceAccount:
  create: true
serviceMonitor:
  create: false
  interval: 20s
  namespace: monitoring
  port: 8080
