replicaCount: 1

image:
  repository: coralogixrepo
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true

service:
  port: 9090

serviceMonitor:
  create: false
  port: 8080
  namespace: monitoring
  interval: 20s

resources:
  memoryMb: 1024
  cpus: 1

config:
  location: operator.conf
  coralogixApi:
    host: grpc-api.coralogix.com
    port: 443
    tls: true
