config:
  coralogixApi:
    host: grpc-api.coralogix.com # or grpc-api.app.coralogix.in
    port: 443
    tls: true
  location: operator.conf
image:
  pullPolicy: IfNotPresent
  repository: coralogixrepo
  tag: 0.1.9
replicaCount: 1
resources:
  cpus: 1
  memoryMb: 1024
service:
  port: 9090
serviceAccount:
  create: true
serviceMonitor:
  create: false
  interval: 20s
  namespace: monitoring
  port: 8080
