name: 'Create a new release'
on:
  release:
    types:
      - published

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Calculate short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install helm-release
        run: |
          helm plugin install https://github.com/sstarcher/helm-release

      - name: Describe
        run: |
          git describe --all

      - name: Helm release
        run: |
          helm release charts/cx-operator

      - name: Tag Docker image
        run: |
          docker pull coralogixrepo/cx-operator:sha-${{ steps.vars.outputs.sha_short }}
          docker tag coralogixrepo/cx-operator:sha-${{ steps.vars.outputs.sha_short }} coralogixrepo/cx-operator:${{ github.event.release.tag_name }}
          docker push coralogixrepo/cx-operator:${{ github.event.release.tag_name }}

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
